name: 'action-generate-docs'
description: 'a GitHub action that allows you to automatically generate Markdown documentation'
runs:
  using: 'node12'
  pre: 'src/pre.js'
  main: 'src/main/main.js'
  post: 'src/post.js'
