name: 'action-generate-docs'
description: 'a GitHub action that allows you to automatically generate Markdown documentation'
inputs:
  type:
    description: 'type of repository to generate the documentation for'
    required: true
  template:
    description: 'the handlebars (.hbs) template you would like to use. The documentation will be injected in place of {{>main}}'
    required: false
runs:
  using: 'node12'
  pre: 'src/pre.js'
  main: 'src/main/main.js'
  post: 'src/post.js'
