name: 'action-generate-docs'
description: 'This action allows you to automatically generate Markdown documentation for your repository'
inputs:
  type:
    description: 'type of repository to generate the documentation for'
    required: true
  template:
    description: 'the template (.md) you would like to use. The documentation will be injected in place of {{>main}}'
    required: false
env:
  FORCE_COLOR:
    description: 'Allows to force colorized output for the documentation preview. Values accepted are ranging from 0 to 3, 3 being the most colorized output and 0 being a non colorized output'
    required: false
    value: 0
runs:
  using: 'node12'
  pre: 'src/pre.js'
  main: 'src/main.js'
  post: 'src/post.js'
